### ISSUE TITLE
Demandas

### ISSUE THREAD

**Issue by sauloantuness** [sauloantuness/bang#2]
**Tipo  de participante**
- Técnico
- Graduação
- Outro

**Instituição**

**Gráfico no ranking**
- Gráfico em barras por participante

**Separação por grupo**

**Comment by sandrord** [comment]
Precisamos disso para a competição que ocorrerá no Inova Minas! 05, 06 e 07/08!

**Comment by sauloantuness** [comment]
This issue was break in another smaller issues.

Duplicate of #26
Duplicate of #24 
Duplicate of #17
